insert into Continant values ('CT001', 'Asia');
insert into Continant values ('CT002', 'Europe');
insert into Continant values ('CT003', 'Africa');
insert into Continant values ('CT004', 'Ocenia');
insert into Continant values ('CT005', 'North America');
insert into Continant values ('CT006', 'Central America');
insert into Continant values ('CT007', 'South America');
insert into Continant values ('CT008', 'Caribbean');

insert into Admin values ('1', 'admin', 'password');

insert into Country values ('CO001', 'Afghanistan', 'Kabul', 'CT001');
insert into Country values ('CO002', 'Australia', 'Canberra', 'CT004');
insert into Country values ('CO003', 'Argentina', 'Beijing', 'CT007');
insert into Country values ('CO004', 'Belize', 'Belmopan', 'CT006');
insert into Country values ('CO005', 'Botswana', 'Gaborone', 'CT003');
insert into Country values ('CO006', 'Brazil', 'Brasilia', 'CT007');
insert into Country values ('CO007', 'Canada', 'Ottawa', 'CT005');
insert into Country values ('CO008', 'Costa Rica', 'San Jose', 'CT006');
insert into Country values ('CO009', 'Croatia', 'Zagreb', 'CT002');
insert into Country values ('CO010', 'Denmark', 'Copehagen', 'CT002');
insert into Country values ('CO011', 'Dominican Republic', 'Santo Domingo', 'CT008');
insert into Country values ('CO012', 'Egypt', 'Cairo', 'CT003');
insert into Country values ('CO013', 'Estonia', 'Talinn', 'CT002');
insert into Country values ('CO014', 'Eswatini', 'Mbabane', 'CT003');
insert into Country values ('CO015', 'Fiji', 'Suva', 'CT004');
insert into Country values ('CO016', 'Finland', 'Helsinki', 'CT002');
insert into Country values ('CO017', 'Ghana', 'Accra', 'CT003');
insert into Country values ('CO018', 'Greece', 'Athens', 'CT002');
insert into Country values ('CO019', 'Guyana', 'Georgetown', 'CT007');
insert into Country values ('CO020', 'Honduras', 'Tegucigalpa', 'CT006');
insert into Country values ('CO021', 'Iceland', 'Reykjavik', 'CT002');
insert into Country values ('CO022', 'Indonesia', 'Jakarta', 'CT001');
insert into Country values ('CO023', 'Italy', 'Rome', 'CT002');
insert into Country values ('CO024', 'Japan', 'Tokyo', 'CT001');
insert into Country values ('CO025', 'Kazakhstan', 'Astana', 'CT001');
insert into Country values ('CO026', 'Kenya', 'Nairobi', 'CT003');
insert into Country values ('CO027', 'Kuwait', 'Kuwait City', 'CT002');
insert into Country values ('CO028', 'Laos', 'Vientiane', 'CT001');
insert into Country values ('CO029', 'Lesotho', 'Maseru', 'CT003');
insert into Country values ('CO030', 'Luxembourg', 'Luxembourg', 'CT002');
insert into Country values ('CO031', 'Madagascar', 'Antananarivo', 'CT003');
insert into Country values ('CO032', 'Mexico', 'Mexico City', 'CT005');
insert into Country values ('CO033', 'Micronesia', 'Palikir', 'CT004');
insert into Country values ('CO034', 'Nauru', 'Yaren', 'CT004');
insert into Country values ('CO035', 'Nicaragua', 'Managua', 'CT006');
insert into Country values ('CO036', 'North Macedonia', 'Skopje', 'CT002');
insert into Country values ('CO037', 'Oman', 'Muscat', 'CT001');
insert into Country values ('CO038', 'Pakistan', 'Islamabad', 'CT001');
insert into Country values ('CO039', 'Peru', 'Lima', 'CT007');
insert into Country values ('CO040', 'Portugal', 'Lisbon', 'CT002');
insert into Country values ('CO041', 'Qatar', 'Doha', 'CT001');
insert into Country values ('CO042', 'Russia', 'Moscow', 'CT002');
insert into Country values ('CO043', 'Rwanda', 'Kigali', 'CT003');
insert into Country values ('CO044', 'Saint Lucia', 'Castries', 'CT008');
insert into Country values ('CO045', 'South Africa', 'Cape Town', 'CT003');
insert into Country values ('CO046', 'Switzerland', 'Bern', 'CT002');
insert into Country values ('CO047', 'Tajikistan', 'Dushanbe', 'CT001');
insert into Country values ('CO048', 'Togo', 'Lome', 'CT003');
insert into Country values ('CO049', 'Trinidad and Tabago', 'Port of Spain', 'CT008');
insert into Country values ('CO050', 'Uganda', 'Kampala', 'CT003');
insert into Country values ('CO051', 'United Kingdom', 'London', 'CT002');
insert into Country values ('CO052', 'Uruguay', 'Montevideo', 'CT007');
insert into Country values ('CO053', 'Vanuatu', 'Port Vila', 'CT004');
insert into Country values ('CO054', 'Venezuela', 'Caracas', 'CT007');
insert into Country values ('CO055', 'Yemen', 'Sanaa', 'CT001');
insert into Country values ('CO056', 'Zambia', 'Lusaka', 'CT003');
insert into Country values ('CO057', 'Zimbabwe', 'Harare', 'CT003');
