version: '3.7'
services: 
  app:
    build: .
    ports:
      - target: 5000
        published: 80
        protocol: tcp
    depends_on:
      - mysql

  mysql: 
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - type: volume
        source: app-volume
        target: /var/lib/mysql
volumes:
  app-volume:
