apiVersion: v1
kind: Pod
metadata:
  name: flask-blog-mysql
  labels:
    app: flask-blog-mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: MYSQL_USER
      value: root
    - name: MYSQL_PASSWORD
      value: root
    - name: MYSQL_DATABASE
      value: GuessTheWorld
---
apiVersion: v1
kind: Service
metadata:
  name: flask-blog-mysql
spec:
  selector:
    app: flask-blog-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
